pipeline {
    agent any
    stages {
        stage('init'){
            steps{
                echo 'Hi, this is Thomas from GIE Sesam Vitale'
                echo 'We are Starting the Test'
            }
        }
        stage('Build'){
            steps{
                echo  'Building Sample Maven Project'
            }
        }
        stage('Deploy'){
            steps{
                echo  'Deploying in staging area'
            }
        }
//         stage('Build Application') {
//             steps {
//                 sh 'mvn -f java-tomcat-sample/pom.xml clean package'
//             }
//             post {
//                 success {
//                     echo "Now Archiving the Artifacts...."
//                     archiveArtifacts artifacts: '**/*.war'
//                 }
//             }
//         }
//         stage('Deploy in Staging Environment'){
//             steps{
//                 build job: 'Deploy_Application_Staging_Env'
//
//             }
//
//         }
//         stage('Deploy to Production'){
//             steps{
//                 timeout(time:5, unit:'DAYS'){
//                     input message:'Approve PRODUCTION Deployment?'
//                 }
//                 build job: 'Deploy_Application_Prod_Env'
//             }
//         }
    }
}